swarna/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'writings/', include('writings.urls')),
    url(r'^about/$', views.about),
    url('', views.homepage),
]

writings/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'writings'

urlpatterns = [
    url(r'^$', views.writings_list, name="list"),
    url(r'^(?P<slug>[\w-]+)/$', views.writings_detail, name="detail"),
]

projects/models.py
from django.db import models

# Create your models here.

writings/models.py
from django.db import models


# Create your models here.
class Writing(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '.......'

projects/views.py
from django.shortcuts import render

# Create your views here.

swarna/views.py
from django.shortcuts import render, HttpResponse


# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')
    #return HttpResponse('homepage')


def about(request):
    return render(request, 'about.html')
    #return HttpResponse('about')

writings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Writing


# Create your views here.

def writings_list(request):
    writings = Writing.objects.all().order_by('date')
    return render(request, 'writings/writings_list.html', {'writings': writings})


def writings_detail(request, slug):
    #return HttpResponse(slug)
    writing = Writing.objects.get(slug=slug)
    return render(request, 'writings/writing_detail.html', {'writing': writing})

templates/about.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'about/style.css'%}">

    <title>about</title>
    <style>
        body {background-color: #010820;}
        /* side navigation bar styling */

* {
    margin: 0;
    padding: 0;
    list-style: none;
    text-decoration: none;
  }

.sidebar {
    position: fixed;
    left: -250px;
    width: 200px;
    height: 100%;
    background: #042331;
    transition: all .5s ease;
    }

.sidebar ul a {
    display: block;
    height: 100%;
    width: 100%;
    line-height: 65px;
    font-size: 20px;
    color: white;
    padding-left: 50px;
    text-decoration: none;
    box-sizing: border-box;
    border-top: 1px solid rgba(255, 255, 255, .1);
    border-bottom: 1px solid black;
    }

ul li a:hover{
        color: rgb(132, 136, 190);
    }

#check {
    display: none;
    }

label #btn, label #cancel{
    position: absolute;
    cursor: pointer;
    background: #042331;
    border-radius: 3px;
    }

label #btn{
    left: 40px;
    top: 25px;
    font-size: 35px;
    color: white;
    padding: 6px 12px;
    transition: all .5s;
    }

label #cancel{
    z-index: 1111;
    left: -155px;
    top: 17px;
    font-size: 30px;
    color: #5220a3;
    padding: 4px 9px;
    }

#check:checked ~ .sidebar{
    left: 0;
    }

#check:checked ~ label #btn {
    left: 250px;
    opacity: 0;
    pointer-events: none;
    }

#check:checked ~ label #cancel {
    left: 155px;
    }


    </style>

</head>
<body>

<input type="checkbox" id="check">
<label for="check">
    <i class="fas fa-bars" id="btn"></i>
    <i class="fas fa-times" id="cancel"></i>

</label>
<div class="sidebar">
    <ul>
        <li><a href=""><i class="fas fa-home"></i> Home </a></li>
        <li><a href="project"> <i class="fas fa-sliders-h"></i> Projects</a></li>
        <li><a href="writings"><i class="fas fa-newspaper"></i> Writings</a></li>
        <li><a href="about"> <i class="far fa-question-circle"></i> About Me</a></li>
    </ul>

</div>


</body>
</html>

templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Writings</title>

</head>
<body>

    <div class="wrapper">
        {% block content %}
        {% endblock %}

    </div>

</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
<h1>hjjjjjjjjjjjjjjjjjjjjjjjjjjhhhhhhhhht6tyyyyyyyyyyyyyyyyyyyyyyyyyyy</h1>

</body>
</html>

writings/templates/writings/writing_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article_detail">
    <div class="article">
        <h2> {{writing.title}} </h2>
        <p> {{writing.body}} </p>
        <p> {{writing.date}} </p>

    </div>
</div>
{% endblock %}

writings/templates/writings/writings_list.html
{% extends 'base_layout.html'%}

{% block content %}
<h1> Writings list</h1>

<div class="writings">
    {% for writing in writings %}
    <div class="writing">
        <h2><a href="{% url 'writings:detail' slug=writing.slug %}"> {{ writing.title }} </a></h2>
        <p>{{ writing.snippet }}</p>
        <p>{{ writing.date }}</p>
    </div>
    {% endfor %}

</div>

{% endblock %}